#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using Malldub.Data;

namespace Malldub.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class InvoiceItemController : ApiController
    {
        private Malldub.Data.MalldubDataContext _context = new Malldub.Data.MalldubDataContext();

        #region Get

        public Malldub.Data.InvoiceItem GetByKey(System.Int32 identification)
        {
            var invoiceItem = _context.InvoiceItem.GetByKey(identification);
            if (invoiceItem == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return invoiceItem;
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetAll()
        {
            return _context.InvoiceItem.AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByInvoiceId(System.Int32 invoiceId)
        {
            return _context.InvoiceItem.ByInvoiceId(invoiceId).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByPaymentItemId(System.Int32 paymentItemId)
        {
            return _context.InvoiceItem.ByPaymentItemId(paymentItemId).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByQuantity(System.Byte quantity)
        {
            return _context.InvoiceItem.ByQuantity(quantity).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByAmount(System.Decimal amount)
        {
            return _context.InvoiceItem.ByAmount(amount).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByDiscountValue(System.Decimal? discountValue)
        {
            return _context.InvoiceItem.ByDiscountValue(discountValue).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByDiscountPercentage(System.Byte? discountPercentage)
        {
            return _context.InvoiceItem.ByDiscountPercentage(discountPercentage).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByDateEntered(System.DateTime? dateEntered)
        {
            return _context.InvoiceItem.ByDateEntered(dateEntered).AsQueryable();
        }

        public IQueryable<Malldub.Data.InvoiceItem> GetByDateUpdated(System.DateTime? dateUpdated)
        {
            return _context.InvoiceItem.ByDateUpdated(dateUpdated).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(Malldub.Data.InvoiceItem value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.InvoiceItem.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<Malldub.Data.InvoiceItem>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(Malldub.Data.InvoiceItem value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var invoiceItem = _context.InvoiceItem.GetByKey(value.Identification);
            if (invoiceItem == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(invoiceItem.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Int32 identification)
        {
            var invoiceItem = _context.InvoiceItem.GetByKey(identification);
            if (invoiceItem == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.InvoiceItem.DeleteObject(invoiceItem);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
