#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using CodeSmith.Data.Linq;
using CodeSmith.Data.Linq.Dynamic;
using Malldub.Data;

namespace Malldub.Data.Controllers.API
{
    [CodeSmith.Data.Web.Http.PagingAndFiltering]
    public partial class PostReplyEmailTypeController : ApiController
    {
        private Malldub.Data.MalldubDataContext _context = new Malldub.Data.MalldubDataContext();

        #region Get

        public Malldub.Data.PostReplyEmailType GetByKey(System.Int32 identification)
        {
            var postReplyEmailType = _context.PostReplyEmailType.GetByKey(identification);
            if (postReplyEmailType == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            return postReplyEmailType;
        }

        public IQueryable<Malldub.Data.PostReplyEmailType> GetAll()
        {
            return _context.PostReplyEmailType.AsQueryable();
        }

        public IQueryable<Malldub.Data.PostReplyEmailType> GetByDetails(System.String details)
        {
            return _context.PostReplyEmailType.ByDetails(details).AsQueryable();
        }

        public IQueryable<Malldub.Data.PostReplyEmailType> GetByDescription(System.String description)
        {
            return _context.PostReplyEmailType.ByDescription(description).AsQueryable();
        }

        #endregion

        public HttpResponseMessage Post(Malldub.Data.PostReplyEmailType value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            _context.PostReplyEmailType.AddObject(value);
            _context.SaveChanges();

            var response = Request.CreateResponse<Malldub.Data.PostReplyEmailType>(HttpStatusCode.Created, value);
            response.Headers.Location = new Uri( Url.Link("DefaultApi", new { Identification = value.Identification }));

            return response;
        }

        public HttpResponseMessage Put(Malldub.Data.PostReplyEmailType value)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.BadRequest));

            var postReplyEmailType = _context.PostReplyEmailType.GetByKey(value.Identification);
            if (postReplyEmailType == null)
                throw new HttpResponseException(new HttpResponseMessage(HttpStatusCode.NotFound));

            _context.ApplyCurrentValues(postReplyEmailType.EntityKey.EntitySetName, value);
            _context.SaveChanges();

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        public HttpResponseMessage Delete(System.Int32 identification)
        {
            var postReplyEmailType = _context.PostReplyEmailType.GetByKey(identification);
            if (postReplyEmailType == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            _context.PostReplyEmailType.DeleteObject(postReplyEmailType);
            _context.SaveChanges();
            
            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}
