#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Malldub.Data
{
    [EdmEntityTypeAttribute(NamespaceName="Malldub.Data", Name="Address")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class Address : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new Address object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="address1">Initial value of the Address1 property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zipCode">Initial value of the ZipCode property.</param>
        public static Address CreateAddress(global::System.Int32 identification, global::System.String address1, global::System.String city, global::System.String state, global::System.String zipCode)
        {
            Address address = new Address();
            address.Identification = identification;
            address.Address1 = address1;
            address.City = city;
            address.State = state;
            address.ZipCode = zipCode;

            return address;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Int32 _identification;
        partial void OnIdentificationChanging(global::System.Int32 value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _address1;
            }
            set
            {
                if (_address1 != value)
                {
                    OnAddress1Changing(value);
                    ReportPropertyChanging("Address1");
                    _address1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Address1");
                    OnAddress1Changed();
                }
            }
        }

        private global::System.String _address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _address2;
            }
            set
            {
                if (_address2 != value)
                {
                    OnAddress2Changing(value);
                    ReportPropertyChanging("Address2");
                    _address2 = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Address2");
                    OnAddress2Changed();
                }
            }
        }

        private global::System.String _address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _city;
            }
            set
            {
                if (_city != value)
                {
                    OnCityChanging(value);
                    ReportPropertyChanging("City");
                    _city = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("City");
                    OnCityChanged();
                }
            }
        }

        private global::System.String _city;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _state;
            }
            set
            {
                if (_state != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _state = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }

        private global::System.String _state;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _zipCode;
            }
            set
            {
                if (_zipCode != value)
                {
                    OnZipCodeChanging(value);
                    ReportPropertyChanging("ZipCode");
                    _zipCode = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ZipCode");
                    OnZipCodeChanged();
                }
            }
        }

        private global::System.String _zipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Decimal? Longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                if (_longitude != value)
                {
                    OnLongitudeChanging(value);
                    ReportPropertyChanging("Longitude");
                    _longitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Longitude");
                    OnLongitudeChanged();
                }
            }
        }

        private global::System.Decimal? _longitude;
        partial void OnLongitudeChanging(global::System.Decimal? value);
        partial void OnLongitudeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Decimal? Latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                if (_latitude != value)
                {
                    OnLatitudeChanging(value);
                    ReportPropertyChanging("Latitude");
                    _latitude = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Latitude");
                    OnLatitudeChanged();
                }
            }
        }

        private global::System.Decimal? _latitude;
        partial void OnLatitudeChanging(global::System.Decimal? value);
        partial void OnLatitudeChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String County
        {
            get
            {
                return _county;
            }
            set
            {
                if (_county != value)
                {
                    OnCountyChanging(value);
                    ReportPropertyChanging("County");
                    _county = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("County");
                    OnCountyChanged();
                }
            }
        }

        private global::System.String _county;
        partial void OnCountyChanging(global::System.String value);
        partial void OnCountyChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Country
        {
            get
            {
                return _country;
            }
            set
            {
                if (_country != value)
                {
                    OnCountryChanging(value);
                    ReportPropertyChanging("Country");
                    _country = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Country");
                    OnCountryChanged();
                }
            }
        }

        private global::System.String _country;
        partial void OnCountryChanging(global::System.String value);
        partial void OnCountryChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? DateEntered
        {
            get
            {
                return _dateEntered;
            }
            set
            {
                if (_dateEntered != value)
                {
                    OnDateEnteredChanging(value);
                    ReportPropertyChanging("DateEntered");
                    _dateEntered = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateEntered");
                    OnDateEnteredChanged();
                }
            }
        }

        private global::System.DateTime? _dateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime? value);
        partial void OnDateEnteredChanged();

        #endregion

        #region Navigation Properties

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_Order_Billing_Address", "Order")]
        public EntityCollection<Order> BillingAddressOrderList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("Malldub.Data.FK_Order_Billing_Address", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("Malldub.Data.FK_Order_Billing_Address", "Order", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_Order_Shipping_Address", "Order")]
        public EntityCollection<Order> ShippingAddressOrderList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("Malldub.Data.FK_Order_Shipping_Address", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("Malldub.Data.FK_Order_Shipping_Address", "Order", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_UserAddress_Address", "UserAddress")]
        public EntityCollection<UserAddress> UserAddressList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserAddress>("Malldub.Data.FK_UserAddress_Address", "UserAddress");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserAddress>("Malldub.Data.FK_UserAddress_Address", "UserAddress", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_Address_State", "State")]
        public State StateMember
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("Malldub.Data.FK_Address_State", "State").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("Malldub.Data.FK_Address_State", "State").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<State> StateMemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<State>("Malldub.Data.FK_Address_State", "State");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<State>("Malldub.Data.FK_Address_State", "State", value);
                }
            }
        }

        #endregion
    }
}
#pragma warning restore 1591