#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Malldub.Data
{
    [EdmEntityTypeAttribute(NamespaceName="Malldub.Data", Name="Comment")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class Comment : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new Comment object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="dateEntered">Initial value of the DateEntered property.</param>
        public static Comment CreateComment(global::System.Int32 identification, global::System.DateTime dateEntered)
        {
            Comment comment = new Comment();
            comment.Identification = identification;
            comment.DateEntered = dateEntered;

            return comment;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Int32 _identification;
        partial void OnIdentificationChanging(global::System.Int32 value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Post
        {
            get
            {
                return _post;
            }
            set
            {
                if (_post != value)
                {
                    OnPostChanging(value);
                    ReportPropertyChanging("Post");
                    _post = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Post");
                    OnPostChanged();
                }
            }
        }

        private global::System.String _post;
        partial void OnPostChanging(global::System.String value);
        partial void OnPostChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _userId = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }

        private global::System.String _userId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? GeoId
        {
            get
            {
                return _geoId;
            }
            set
            {
                if (_geoId != value)
                {
                    OnGeoIdChanging(value);
                    ReportPropertyChanging("GeoId");
                    _geoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GeoId");
                    OnGeoIdChanged();
                }
            }
        }

        private global::System.Int32? _geoId;
        partial void OnGeoIdChanging(global::System.Int32? value);
        partial void OnGeoIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateEntered
        {
            get
            {
                return _dateEntered;
            }
            set
            {
                if (_dateEntered != value)
                {
                    OnDateEnteredChanging(value);
                    ReportPropertyChanging("DateEntered");
                    _dateEntered = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateEntered");
                    OnDateEnteredChanged();
                }
            }
        }

        private global::System.DateTime _dateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime value);
        partial void OnDateEnteredChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _title;
            }
            set
            {
                if (_title != value)
                {
                    OnTitleChanging(value);
                    ReportPropertyChanging("Title");
                    _title = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }

        private global::System.String _title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnNameChanging(value);
                    ReportPropertyChanging("Name");
                    _name = StructuralObject.SetValidValue(value, true);
                    ReportPropertyChanged("Name");
                    OnNameChanged();
                }
            }
        }

        private global::System.String _name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? TotalLikes
        {
            get
            {
                return _totalLikes;
            }
            set
            {
                if (_totalLikes != value)
                {
                    OnTotalLikesChanging(value);
                    ReportPropertyChanging("TotalLikes");
                    _totalLikes = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TotalLikes");
                    OnTotalLikesChanged();
                }
            }
        }

        private global::System.Int32? _totalLikes;
        partial void OnTotalLikesChanging(global::System.Int32? value);
        partial void OnTotalLikesChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PostToFacebook
        {
            get
            {
                return _postToFacebook;
            }
            set
            {
                if (_postToFacebook != value)
                {
                    OnPostToFacebookChanging(value);
                    ReportPropertyChanging("PostToFacebook");
                    _postToFacebook = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostToFacebook");
                    OnPostToFacebookChanged();
                }
            }
        }

        private global::System.Boolean _postToFacebook;
        partial void OnPostToFacebookChanging(global::System.Boolean value);
        partial void OnPostToFacebookChanged();

        #endregion

        #region Navigation Properties

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_Comment_AspNetUser", "AspNetUser")]
        public AspNetUser AspNetUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_Comment_AspNetUser", "AspNetUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_Comment_AspNetUser", "AspNetUser").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AspNetUser> AspNetUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_Comment_AspNetUser", "AspNetUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AspNetUser>("Malldub.Data.FK_Comment_AspNetUser", "AspNetUser", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_Comment_Geo", "Geo")]
        public Geo Geo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Geo>("Malldub.Data.FK_Comment_Geo", "Geo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Geo>("Malldub.Data.FK_Comment_Geo", "Geo").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Geo> GeoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Geo>("Malldub.Data.FK_Comment_Geo", "Geo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Geo>("Malldub.Data.FK_Comment_Geo", "Geo", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundComment_Comment", "FundComment")]
        public EntityCollection<FundComment> FundCommentList
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FundComment>("Malldub.Data.FK_FundComment_Comment", "FundComment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FundComment>("Malldub.Data.FK_FundComment_Comment", "FundComment", value);
                }
            }
        }

        #endregion
    }
}
#pragma warning restore 1591