#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Malldub.Data
{
    [EdmEntityTypeAttribute(NamespaceName="Malldub.Data", Name="FundComment")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class FundComment : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new FundComment object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="fundId">Initial value of the FundId property.</param>
        /// <param name="commentId">Initial value of the CommentId property.</param>
        /// <param name="originId">Initial value of the OriginId property.</param>
        public static FundComment CreateFundComment(global::System.Int32 identification, global::System.Int32 fundId, global::System.Int32 commentId, global::System.String originId)
        {
            FundComment fundComment = new FundComment();
            fundComment.Identification = identification;
            fundComment.FundId = fundId;
            fundComment.CommentId = commentId;
            fundComment.OriginId = originId;

            return fundComment;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Int32 _identification;
        partial void OnIdentificationChanging(global::System.Int32 value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FundId
        {
            get
            {
                return _fundId;
            }
            set
            {
                if (_fundId != value)
                {
                    OnFundIdChanging(value);
                    ReportPropertyChanging("FundId");
                    _fundId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FundId");
                    OnFundIdChanged();
                }
            }
        }

        private global::System.Int32 _fundId;
        partial void OnFundIdChanging(global::System.Int32 value);
        partial void OnFundIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CommentId
        {
            get
            {
                return _commentId;
            }
            set
            {
                if (_commentId != value)
                {
                    OnCommentIdChanging(value);
                    ReportPropertyChanging("CommentId");
                    _commentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentId");
                    OnCommentIdChanged();
                }
            }
        }

        private global::System.Int32 _commentId;
        partial void OnCommentIdChanging(global::System.Int32 value);
        partial void OnCommentIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginId
        {
            get
            {
                return _originId;
            }
            set
            {
                if (_originId != value)
                {
                    OnOriginIdChanging(value);
                    ReportPropertyChanging("OriginId");
                    _originId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("OriginId");
                    OnOriginIdChanged();
                }
            }
        }

        private global::System.String _originId;
        partial void OnOriginIdChanging(global::System.String value);
        partial void OnOriginIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Int32? DonationId
        {
            get
            {
                return _donationId;
            }
            set
            {
                if (_donationId != value)
                {
                    OnDonationIdChanging(value);
                    ReportPropertyChanging("DonationId");
                    _donationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DonationId");
                    OnDonationIdChanged();
                }
            }
        }

        private global::System.Int32? _donationId;
        partial void OnDonationIdChanging(global::System.Int32? value);
        partial void OnDonationIdChanged();

        #endregion

        #region Navigation Properties

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundComment_Comment", "Comment")]
        public Comment Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("Malldub.Data.FK_FundComment_Comment", "Comment").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("Malldub.Data.FK_FundComment_Comment", "Comment").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Comment> CommentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comment>("Malldub.Data.FK_FundComment_Comment", "Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Comment>("Malldub.Data.FK_FundComment_Comment", "Comment", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundComment_Fund", "Fund")]
        public Fund Fund
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundComment_Fund", "Fund").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundComment_Fund", "Fund").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fund> FundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundComment_Fund", "Fund");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fund>("Malldub.Data.FK_FundComment_Fund", "Fund", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundComment_FundCommentOrigin", "FundCommentOrigin")]
        public FundCommentOrigin FundCommentOrigin
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundCommentOrigin>("Malldub.Data.FK_FundComment_FundCommentOrigin", "FundCommentOrigin").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundCommentOrigin>("Malldub.Data.FK_FundComment_FundCommentOrigin", "FundCommentOrigin").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FundCommentOrigin> FundCommentOriginReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundCommentOrigin>("Malldub.Data.FK_FundComment_FundCommentOrigin", "FundCommentOrigin");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FundCommentOrigin>("Malldub.Data.FK_FundComment_FundCommentOrigin", "FundCommentOrigin", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundComment_Donation", "Donation")]
        public Donation Donation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Donation>("Malldub.Data.FK_FundComment_Donation", "Donation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Donation>("Malldub.Data.FK_FundComment_Donation", "Donation").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Donation> DonationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Donation>("Malldub.Data.FK_FundComment_Donation", "Donation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Donation>("Malldub.Data.FK_FundComment_Donation", "Donation", value);
                }
            }
        }

        #endregion
    }
}
#pragma warning restore 1591