#pragma warning disable 1591
// <auto-generated>
//     This code was generated from a CodeSmith Generator template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;
using System.Xml.Serialization;

namespace Malldub.Data
{
    [EdmEntityTypeAttribute(NamespaceName="Malldub.Data", Name="FundUpdate")]
    [DataContractAttribute(IsReference=true)]
    [ScaffoldTable(true)]
    [Serializable()]
    public partial class FundUpdate : EntityObject
    {
        #region Factory Methods

        /// <summary>
        /// Create a new FundUpdate object.
        /// </summary>
        /// <param name="identification">Initial value of the Identification property.</param>
        /// <param name="fundId">Initial value of the FundId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="statusId">Initial value of the StatusId property.</param>
        /// <param name="postedToFacebook">Initial value of the PostedToFacebook property.</param>
        /// <param name="postedToEmail">Initial value of the PostedToEmail property.</param>
        /// <param name="postedToTwitter">Initial value of the PostedToTwitter property.</param>
        public static FundUpdate CreateFundUpdate(global::System.Int32 identification, global::System.Int32 fundId, global::System.String userId, global::System.String title, global::System.String content, global::System.String statusId, global::System.Boolean postedToFacebook, global::System.Boolean postedToEmail, global::System.Boolean postedToTwitter)
        {
            FundUpdate fundUpdate = new FundUpdate();
            fundUpdate.Identification = identification;
            fundUpdate.FundId = fundId;
            fundUpdate.UserId = userId;
            fundUpdate.Title = title;
            fundUpdate.Content = content;
            fundUpdate.StatusId = statusId;
            fundUpdate.PostedToFacebook = postedToFacebook;
            fundUpdate.PostedToEmail = postedToEmail;
            fundUpdate.PostedToTwitter = postedToTwitter;

            return fundUpdate;
        }

        #endregion

        #region Primitive Properties

        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Identification
        {
            get
            {
                return _identification;
            }
            set
            {
                if (_identification != value)
                {
                    OnIdentificationChanging(value);
                    ReportPropertyChanging("Identification");
                    _identification = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Identification");
                    OnIdentificationChanged();
                }
            }
        }

        private global::System.Int32 _identification;
        partial void OnIdentificationChanging(global::System.Int32 value);
        partial void OnIdentificationChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FundId
        {
            get
            {
                return _fundId;
            }
            set
            {
                if (_fundId != value)
                {
                    OnFundIdChanging(value);
                    ReportPropertyChanging("FundId");
                    _fundId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FundId");
                    OnFundIdChanged();
                }
            }
        }

        private global::System.Int32 _fundId;
        partial void OnFundIdChanging(global::System.Int32 value);
        partial void OnFundIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserId
        {
            get
            {
                return _userId;
            }
            set
            {
                if (_userId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _userId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }

        private global::System.String _userId;
        partial void OnUserIdChanging(global::System.String value);
        partial void OnUserIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _title;
            }
            set
            {
                if (_title != value)
                {
                    OnTitleChanging(value);
                    ReportPropertyChanging("Title");
                    _title = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }

        private global::System.String _title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Content
        {
            get
            {
                return _content;
            }
            set
            {
                if (_content != value)
                {
                    OnContentChanging(value);
                    ReportPropertyChanging("Content");
                    _content = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Content");
                    OnContentChanged();
                }
            }
        }

        private global::System.String _content;
        partial void OnContentChanging(global::System.String value);
        partial void OnContentChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StatusId
        {
            get
            {
                return _statusId;
            }
            set
            {
                if (_statusId != value)
                {
                    OnStatusIdChanging(value);
                    ReportPropertyChanging("StatusId");
                    _statusId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StatusId");
                    OnStatusIdChanged();
                }
            }
        }

        private global::System.String _statusId;
        partial void OnStatusIdChanging(global::System.String value);
        partial void OnStatusIdChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.DateTime? DateEntered
        {
            get
            {
                return _dateEntered;
            }
            set
            {
                if (_dateEntered != value)
                {
                    OnDateEnteredChanging(value);
                    ReportPropertyChanging("DateEntered");
                    _dateEntered = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DateEntered");
                    OnDateEnteredChanged();
                }
            }
        }

        private global::System.DateTime? _dateEntered;
        partial void OnDateEnteredChanging(global::System.DateTime? value);
        partial void OnDateEnteredChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PostedToFacebook
        {
            get
            {
                return _postedToFacebook;
            }
            set
            {
                if (_postedToFacebook != value)
                {
                    OnPostedToFacebookChanging(value);
                    ReportPropertyChanging("PostedToFacebook");
                    _postedToFacebook = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostedToFacebook");
                    OnPostedToFacebookChanged();
                }
            }
        }

        private global::System.Boolean _postedToFacebook;
        partial void OnPostedToFacebookChanging(global::System.Boolean value);
        partial void OnPostedToFacebookChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PostedToEmail
        {
            get
            {
                return _postedToEmail;
            }
            set
            {
                if (_postedToEmail != value)
                {
                    OnPostedToEmailChanging(value);
                    ReportPropertyChanging("PostedToEmail");
                    _postedToEmail = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostedToEmail");
                    OnPostedToEmailChanged();
                }
            }
        }

        private global::System.Boolean _postedToEmail;
        partial void OnPostedToEmailChanging(global::System.Boolean value);
        partial void OnPostedToEmailChanged();

        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PostedToTwitter
        {
            get
            {
                return _postedToTwitter;
            }
            set
            {
                if (_postedToTwitter != value)
                {
                    OnPostedToTwitterChanging(value);
                    ReportPropertyChanging("PostedToTwitter");
                    _postedToTwitter = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostedToTwitter");
                    OnPostedToTwitterChanged();
                }
            }
        }

        private global::System.Boolean _postedToTwitter;
        partial void OnPostedToTwitterChanging(global::System.Boolean value);
        partial void OnPostedToTwitterChanged();

        #endregion

        #region Navigation Properties

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundUpdate_Fund", "Fund")]
        public Fund Fund
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundUpdate_Fund", "Fund").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundUpdate_Fund", "Fund").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Fund> FundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Fund>("Malldub.Data.FK_FundUpdate_Fund", "Fund");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Fund>("Malldub.Data.FK_FundUpdate_Fund", "Fund", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundUpdate_FundUpdateStatus", "FundUpdateStatus")]
        public FundUpdateStatus FundUpdateStatus
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundUpdateStatus>("Malldub.Data.FK_FundUpdate_FundUpdateStatus", "FundUpdateStatus").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundUpdateStatus>("Malldub.Data.FK_FundUpdate_FundUpdateStatus", "FundUpdateStatus").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FundUpdateStatus> FundUpdateStatusReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FundUpdateStatus>("Malldub.Data.FK_FundUpdate_FundUpdateStatus", "FundUpdateStatus");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FundUpdateStatus>("Malldub.Data.FK_FundUpdate_FundUpdateStatus", "FundUpdateStatus", value);
                }
            }
        }

        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Malldub.Data", "FK_FundUpdate_User", "AspNetUser")]
        public AspNetUser AspNetUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_FundUpdate_User", "AspNetUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_FundUpdate_User", "AspNetUser").Value = value;
            }
        }

        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<AspNetUser> AspNetUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<AspNetUser>("Malldub.Data.FK_FundUpdate_User", "AspNetUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<AspNetUser>("Malldub.Data.FK_FundUpdate_User", "AspNetUser", value);
                }
            }
        }

        #endregion
    }
}
#pragma warning restore 1591